#spring:
#  application:
#    name: zuul-service
#
#server:
#  port: 8762
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    enabled: true
#    fetch-registry: true
#
#zuul:
#  ignored-services: "*"
#  routes:
#    auth-service:
#      path: /users/**
#      service-id: user-service
#      strip-prefix: false
#    user-service:
#      sensitive-headers: Cookie,Set-Cookie
#
#    product-service:
#      path: /products/**
#      service-id: product-service
#      sensitive-headers: Cookie,Set-Cookie
#  prefix: /api/v1
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"